sudo: required
dist: trusty
osx_image: xcode8.3
language: c
before_install:
- sudo apt-get -qq update
cache:
  directories:
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - icnsutils
    - graphicsmagick
    - libgnome-keyring-dev
    - xz-utils
    - xorriso
    - xvfb
install:
- sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib
- sudo nvm install 6
- sudo npm install
- sudo npm install electron-builder@next
- sudo npm install electron -g
- sudo npm install
- sudo export DISPLAY=':99.0'
- sudo Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start &
- sleep 3
script:
- node_modules/.bin/electron-builder build
group: stable
compiler: clang
env: CC=clang CXX=clang++ npm_config_clang=1
os: linux
