sudo: required
dist: trusty
osx_image: xcode8.3
language: c

services:
  - docker

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

node_js:
  - 6

before_install:
  - apt-get -qq update

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - libgnome-keyring-dev
      - xz-utils
      - xorriso
      - xvfb

install:
  - apt-get install --no-install-recommends -y gcc-multilib g++-multilib
  - nvm install 6
  - npm install
  - npm install electron-builder@next
  - npm install electron -g
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - node_modules/.bin/electron-builder build